name: Deploy Express API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /var/www/apps/vshri-express-api

            git pull origin main

            npm install

            if pm2 describe vshri-api > /dev/null; then
              pm2 restart vshri-api
            else
              pm2 start server.js --name vshri-api
            fi

            pm2 save

            echo "Deployment completed successfully."